name: Notify

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Publish repository dispatch
        uses: ibm-garage-cloud/action-repository-dispatch@main
        with:
          notifyRepo: cloud-native-toolkit/terraform-tools-dashboard
          eventType: released
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}